### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Daste745** [Daste745/nagatoro#2]
Settings will make Nagatoro more customizable and allow guild owners to disable certain functions or block the bot from posting in channels they desire to remain bot-free.

- [x] Disable all commands in certain channels
- [x] Disable level up messages
- [ ] Disable channels from giving exp (like #spam or #bots)
- [x] Set guild timezone and/or locale

**Comment by Stefankar1000** [comment]
The feature with disabling commands in channels might just be unnecessary. Everyone can just disable bot's access to any channel with channel permissions. Either drop this feature or consider updating channel permissions (I'm not sure if disabling your own permissions is possible) instead of keeping a disable list in the database.
When it comes to point 2, I'm thinking of removing level up messages entirely, because they don't really provide any useful information and 90% of bigger guilds would probably turn them off.
Point 3: This is already partly in place (Messages of 5 or less in length, valid commands, and messages in channels named '#spam' are ignored when counting exp), but will need to be replaced with a more custom solution once #3 is implemented.
